# Dependencies
kramdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            winfan
tagline:          'A blog lazybug?'
description:      'free in net world'
url:              http://giftman.github.io
baseurl:          /

author:
  name:           'winfan'
  url:            http://giftman.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/giftman/giftman.github.io
